[CXF-4045] Updating BusFactory to catch NoClassDefFoundError with minor refactoring to pass the Checkstyle
git-svn-id: https://svn.apache.org/repos/asf/cxf/trunk@1233355 13f79535-47bb-0310-9956-ffa450edef68

Former-commit-id: 2ac06a49941ed13512404bd8cd13f330e32fc995